CREATE TABLE `student` (
 `USERNAME` varchar(30) NOT NULL,
 `PASSWRD` varchar(100) DEFAULT NULL,
 `CONFIRMPASSWRD` varchar(100) DEFAULT NULL,
 `THE_TOKEN` varchar(100) DEFAULT NULL,
 `ONTIME` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4